version: "2"
services:
  python-flask:
    build:
      # Specify our app directory as the context
      context: ./BackPython
      # Use the Dockerfile that exists within the directory we specified above
      dockerfile: ./Dockerfile
    ports:
      # Flask server
      - "5000:5000"
      # Flask server debug port
      # - "5678:5678"
    environment:
      # Specify the path within our Docker container that contains our application code
      FLASK_APP: /code/app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      # Map our local directory to our Docker application root so that any changes we make are immediately available
      - ./BackPython/:/code
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./FrontNextjsReact/todo
      dockerfile: Dockerfile
    volumes:
      - ./FrontNextjsReact/todo:/app
      # Prevent the node_modules and .next folders in the Docker container from being accidentally overwritten with our initial mapping of our local directory to /usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./FrontNextjsReact/todo/.env.local
    # depends_on:
    #   - python-flask
