version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_USER: 'todo'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - todo-mysql-data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mysql+pymysql://todo:password@db:3306/todo'
      FLASK_ENV: 'development'
      FLASK_APP: 'app.py'

volumes:
  todo-mysql-data: